server:
  port: 8181

spring:
  flyway:
    baselineOnMigrate: true
  sql:
    init:
      platform: postgres
  r2dbc:
    url: jdbc:postgresql://localhost:5432/inventory
    host: localhost
    port: 5432
    database: inventory
    username: postgres
    password: postgres
    pool:
      initial-size: 10
      max-size: 10
      max-idle-time: 30